### ISSUE TITLE
Question about arch setup

### ISSUE THREAD

**Issue by carlosal1015** [da-moon/container-images#1]
Hi @da-moon, I [read the discussion](https://github.com/gitpod-io/gitpod/pull/4900) and I would you like ask if is possible to test an empty like [gitpod-debian-empty-workspace](https://github.com/da-moon/gitpod-debian-empty-workspace) with arch setup (only with dockerfile and gitpod.yml). Thanks a lot

**Comment by da-moon** [comment]
@carlosal1015 So, at this point, I don't think one can uses Arch Linux with Gitpod. I think the main reason is the 'gitpod layer' stage; it tries to run the following [script](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/workspace-image-layer/scripts/detect-distro.sh); as you can see it does not support Arch based distros.

I have submitted a PR [here](https://github.com/gitpod-io/gitpod/pull/4900#issuecomment-886422048) with my updated changes; you can take a look at it yourself [here](https://github.com/da-moon/gitpod/tree/archlinux-gitpod-layer/components/image-builder/workspace-image-layer)

I added base Arch Image, I also fixed the scripts and wrote test-cases to follow their example. they haven't merged it with the master branch so we won't get Arch support until they merge my PR or they remove the whole Gitpod Layer stuff.

**Comment by da-moon** [comment]
you can try creating a test repo yourself and see the problem in action; just use `fjolsvin/gitpod-workspace-full-archlinux` docker image in your `.gitpod.yml` file, the image would load but it would fail at the `gitpod layer` stage

You can also try opening [`gitpod-exp`](https://github.com/da-moon/virtualized-environments/tree/gitpod-exp) branch of this repo in Gitpod; it is using archlinux image.

**Comment by carlosal1015** [comment]
Oh wow, only debian, ubuntu, linuxmint, amzn and alpine. I thought that was related with [bug related with alpm library](https://www.reddit.com/r/archlinux/comments/lek2ba/arch_linux_on_docker_ci_could_not_find_or_read).

> @carlosal1015 So, at this point, I don't think one can uses Arch Linux with Gitpod. I think the main reason is the 'gitpod layer' stage; it tries to run the following [script](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/workspace-image-layer/scripts/detect-distro.sh); as you can see it does not support Arch based distros.
> 
> I have submitted a PR [here](https://github.com/gitpod-io/gitpod/pull/4900#issuecomment-886422048) with my updated changes; you can take a look at it yourself [here](https://github.com/da-moon/gitpod/tree/archlinux-gitpod-layer/components/image-builder/workspace-image-layer)
> 
> I added base Arch Image, I also fixed the scripts and wrote test-cases to follow their example. they haven't merged it with the master branch so we won't get Arch support until they merge my PR or they remove the whole Gitpod Layer stuff.

I was thinking at the moment is run a .sh file that mount the repo using a docker image like [this](https://github.com/cpp-review-dune/introductory-review/blob/main/src/Docker/DUNEPDELab.Dockerfile#L52).

> you can try creating a test repo yourself and see the problem in action; just use `fjolsvin/gitpod-workspace-full-archlinux` docker image in your `.gitpod.yml` file, the image would load but it would fail at the `gitpod layer` stage
> 
> You can also try opening [`gitpod-exp`](https://github.com/da-moon/virtualized-environments/tree/gitpod-exp) branch of this repo in Gitpod; it is using archlinux image.

Yes I will play with the nice image
```
fjolsvin/gitpod-workspace-full-archlinux                      latest    ad34910ab635   13 hours ago   6.87GB
```

Thank you again. (Closing the question)

**Edited:**

If we add [this patch](https://github.com/the-ashh/build-arch-action/blob/master/Dockerfile#L6), then will not have a problem with alpm library, and yes, it stop working when says adding gitpod layer.

I pull a [new docker image with the patch](https://hub.docker.com/r/carlosal1015/gitpod-workspace-full-archlinux) builded in gitpod changing the name in build.sh and adding the patch in Dockerfile.

![image](https://user-images.githubusercontent.com/21283014/128939768-2ef48e3e-fe12-4a54-8d1e-0bd1bfa86b08.png)

Obviously fail because this gitpod version is not using your pull request, but if gitpod is buiding with your pull request plus patch of glibc, then soon will be part of gitpod core. And then will be works. I was trying with [setup](https://github.com/cpp-review-dune/gitpod-sandbox) similar to the branch `gitpod-exp`.

**Comment by carlosal1015** [comment]
Thank you very much @da-moon , now https://gitpod.io/#https://github.com/da-moon/virtualized-environments/tree/gitpod-exp is working fine 😄
